/**
 * Mapper: Hello-EQ Friction Case submission → PM Graph evaluate request.
 *
 * Defaults applied here (documented below) because HEQ does not currently
 * store difficulty or seniority per submission.
 *
 *   difficulty = 'intermediate'
 *     Friction cases are scenario-based MCQ — conceptually mid-complexity.
 *     Update if HEQ adds a per-case difficulty field.
 *
 *   seniority = 'mid'
 *     HEQ's primary audience is mid-level PMs (2-5 yrs experience).
 *     Update if HEQ adds user seniority to the profile.
 */

import { type PMGraphEvaluateRequest } from './schema.js';

// ── Friction theme — inlined to keep the integration layer self-contained ──────

/** Mirrors FrictionTheme from src/data/frictionCases.ts */
export type FrictionTheme = 'pricing' | 'ux' | 'onboarding' | 'value' | 'trust';

// ── Theme → surface mapping ────────────────────────────────────────────────────

const THEME_TO_SURFACE: Record<FrictionTheme, string> = {
  pricing:    'pricing_page',
  ux:         'product_ux',
  onboarding: 'onboarding_flow',
  value:      'value_proposition',
  trust:      'trust_and_safety',
};

// ── Inbound payload type ───────────────────────────────────────────────────────

/**
 * The Hello-EQ Friction Case submission shape that the API route receives
 * from the frontend. Mirrors the data available at the end of
 * FrictionCaseExercise.handleSave() plus the FrictionCase fields needed
 * to construct the scenario text for PM Graph.
 */
export interface HEQFrictionCaseSubmission {
  /** FrictionCase.id — stable case identifier (e.g. 'fc_001'). */
  caseId: string;
  /** InsightStore submission ID — auto-generated by the client if not yet persisted. */
  submissionId?: string;

  /** Theme used to derive the PM Graph 'surface' field. */
  theme: FrictionTheme;

  /** FrictionCase.context — where in the product journey the friction occurred. */
  context: string;
  /** FrictionCase.narrative — brief PM context for the scenario. */
  narrative: string;
  /** FrictionCase.rawResponse — short anonymised user quote. */
  rawResponse: string;

  /** All root-issue option labels, indexed by position. */
  rootIssueOptions: string[];
  /** Index of the option the user selected for root issue. */
  rootAnswerIndex: number;

  /** All fix option labels, indexed by position. */
  fixOptions: string[];
  /** Index of the option the user selected for fix. */
  fixAnswerIndex: number;

  /** Optional open reflection the user typed before reveal. */
  reflectionText?: string;

  /** Optional product name (present if the case is product-specific). */
  productName?: string;
  /** Optional product context blurb. */
  productContext?: string;
}

// ── Extended PM Graph request ──────────────────────────────────────────────────

/**
 * PM Graph evaluate request extended with friction-case context fields.
 *
 * These fields are not part of the base PMGraphEvaluateRequestSchema but
 * PM Graph accepts (and optionally uses) them for richer evaluation.
 * The base request schema does not use .strict() so extra fields are allowed.
 */
export interface PMGraphFrictionCaseRequest extends PMGraphEvaluateRequest {
  /** PM Graph surface identifier derived from the HEQ friction theme. */
  surface: string;
  /** Full scenario text composed from context + narrative + raw user response. */
  scenario_text: string;
  /** Stable HEQ case ID — enables PM Graph to cache / deduplicate scenarios. */
  hello_eq_exercise_id: string;
  /** Unique submission ID for this evaluation event. */
  hello_eq_submission_id: string;
  /**
   * Case difficulty.
   * Default: 'intermediate' — friction cases are mid-complexity MCQ.
   */
  difficulty: string;
  /**
   * Target seniority level.
   * Default: 'mid' — HEQ's primary audience is mid-level PMs.
   */
  seniority: string;
  product_name?: string;
  product_context?: string;
}

// ── Mapper ─────────────────────────────────────────────────────────────────────

/**
 * Maps a Hello-EQ Friction Case submission onto a PM Graph evaluate request.
 *
 * Answer encoding:
 *   Uses the `answers` (key/value) form since friction cases are multi-part:
 *     root_issue         — the label of the root-issue option the user selected
 *     fix_recommendation — the label of the fix option the user selected
 *     reflection         — free-form reasoning text (omitted if blank)
 */
export function mapFrictionCaseToPMGraphRequest(
  submission: HEQFrictionCaseSubmission,
): PMGraphFrictionCaseRequest {
  const {
    caseId,
    submissionId,
    theme,
    context,
    narrative,
    rawResponse,
    rootIssueOptions,
    rootAnswerIndex,
    fixOptions,
    fixAnswerIndex,
    reflectionText,
    productName,
    productContext,
  } = submission;

  // Resolve option labels — fall back to positional label to avoid empty strings.
  const rootAnswer = rootIssueOptions[rootAnswerIndex] ?? `Option ${rootAnswerIndex + 1}`;
  const fixAnswer  = fixOptions[fixAnswerIndex]         ?? `Option ${fixAnswerIndex + 1}`;

  const answers: Record<string, string> = {
    root_issue:         rootAnswer,
    fix_recommendation: fixAnswer,
  };

  const trimmedReflection = reflectionText?.trim();
  if (trimmedReflection) {
    answers.reflection = trimmedReflection;
  }

  const scenarioText = [
    `Context: ${context}`,
    `User signal: "${rawResponse}"`,
    `Background: ${narrative}`,
  ].join('\n');

  const request: PMGraphFrictionCaseRequest = {
    exercise_type: 'friction_case',
    answers,
    surface:                 THEME_TO_SURFACE[theme] ?? theme,
    scenario_text:           scenarioText,
    hello_eq_exercise_id:    caseId,
    hello_eq_submission_id:  submissionId ?? `auto_${caseId}_${Date.now()}`,
    difficulty:              'intermediate',
    seniority:               'mid',
  };

  if (productName)    request.product_name    = productName;
  if (productContext) request.product_context = productContext;

  return request;
}
